on: [push, pull_request]

name: Continuous integration

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "pip"
      - name: install
        run: pip install -r requirements.txt
      - name: pytest
        run: ENV=test pytest --cov=src
      - name: autopep8
        run: autopep8 -i -r --global-config=setup.cfg ./src
      - name: pylint
        run: pylint --rcfile=setup.cfg ./src
      - name: flake8
        run: flake8 --config=setup.cfg ./src
      - name: mypy
        run: mypy --config-file=setup.cfg ./src
